"""
Memory Distiller (Inspired by vectorize-io/hindsight).
Consolidates raw parsed text (Experiences) into structured markdown entities (Synthesized Entities).
This prevents Agent context dilution when reading massive clinical trial protocols.
"""

import glob
import os

MEMORY_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..", ".workbuddy", "memory")
)
EXPERIENCES_DIR = os.path.join(MEMORY_ROOT, "experiences")
ENTITIES_DIR = os.path.join(MEMORY_ROOT, "synthesized_entities")


def distill_experiences():
    """
    Mock logic for LLM-based distillation.
    In a real run, this would read raw txts from EXPERIENCES_DIR,
    prompt the LLM to extract key facts (e.g. AE Grading Criteria),
    and save them cleanly in ENTITIES_DIR.
    """
    if not os.path.exists(EXPERIENCES_DIR):
        print("No experiences to distill.")
        return

    raw_files = glob.glob(os.path.join(EXPERIENCES_DIR, "*.txt"))

    # Example logic: we just simulate the distillation
    print(f"[Memory Distiller] Found {len(raw_files)} raw experience files.")
    print("[Memory Distiller] Distilling key entities to prevent context dilution...")

    for rf in raw_files:
        basename = os.path.basename(rf).replace(".txt", "")
        entity_path = os.path.join(ENTITIES_DIR, f"{basename}_distilled.md")

        # Here we would normally call an LLM. We'll just write a placeholder.
        with open(entity_path, "w", encoding="utf-8") as f:
            f.write(f"# Distilled Entity: {basename}\n")
            f.write("> Auto-generated by Memory Distiller to reduce LLM context load.\n\n")
            f.write("- **Core Fact 1**: [Placeholder for LLM extraction]\n")
            f.write("- **Core Fact 2**: [Placeholder for LLM extraction]\n")

        print(f"[Memory Distiller] Saved synthesized entity: {entity_path}")


if __name__ == "__main__":
    distill_experiences()
